version: '3.9'

services:
  finovara-gateway:
    build: .
    container_name: finovara-gateway
    ports:
      - "443:8888"
    environment:
      CORE_BACKEND_URL: https://finovara-app:8443
      ACTIVITY_LOG_BACKEND_URL: https://finovara-activity-app:8082
      NOTIFICATION_BACKEND_URL: https://finovara-notification-app:8086
      REPORT_BACKEND_URL: https://finovara-report-app:8083
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
    networks:
      - finovara-network

networks:
  finovara-network:
    external: true
    name: finovara-network
