version: '3.9'

services:
  finovara-report-app:
    build: .
    container_name: finovara-report-app
    ports:
      - "8083:8083"
    environment:
      CORE_BACKEND_URL: https://finovara-app:8443
    restart: always
    networks:
      - finovara-network

networks:
  finovara-network:
    external: true
    name: finovara-network
