server:
  port: 8888
  ssl:
    enabled: true
    key-store: file:/app/localhost.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
    key-alias: 1

application:
  name: api-gateway
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    cache:
      type: redis
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - https://localhost:5173
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowed-headers:
                  - "*"
                exposed-headers:
                  - Authorization
                allow-credentials: true
          default-filters:
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          x-forwarded:
            enabled: true
            for-enabled: true
            host-enabled: true
            proto-enabled: true
            port-enabled: true
            host-append: false
            proto-append: false
            port-append: false
          httpclient:
            ssl:
              use-insecure-trust-manager: true
          routes:
            - id: activity-log-backend
              uri: ${ACTIVITY_LOG_BACKEND_URL}
              predicates:
                - Path=/api/account-activity/**,/api/archive-activities/**

            - id: notification-backend
              uri: ${NOTIFICATION_BACKEND_URL}
              predicates:
                - Path=/api/notification-settings/**,/api/notifications/**

            - id: report-backend
              uri: ${REPORT_BACKEND_URL}
              predicates:
                - Path=/api/reports/**,/api/shared-accounts/reports/financial-report,/api/shared-accounts/report-cache/**,/api/report-cache/**,/api/pdf/**,/api/finance-health-score

            - id: auth_backend
              uri: ${AUTH_BACKEND_URL}
              predicates:
                - Path=/api/auth/**,/api/account-management/**,/api/profile-image/**,/profile-images/**,/api/password-reset/**,/api/contact,/oauth2/**,/login/oauth2/**,/api/account-settings/**,/api/security-settings/**,/api/email-change/**,/api/shared-accounts/users/**

            - id: finance_backend
              uri: ${FINANCE_BACKEND_URL}
              predicates:
                - Path=/**


management:
  server:
    port: 9100
    ssl:
      enabled: false
  endpoint:
    gateway:
      access: read_only
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics,gateway
  metrics:
    tags:
      application: api-gateway
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s

logging:
  level:
    root: WARN
    com.finovara.apigateway: INFO


security:
  whitelist:
    - /api/auth/**
    - /api/profile-image/**
    - /profile-images/**
    - /api/password-reset/**
    - /api/contact
    - /oauth2/**
    - /login/oauth2/**
    - /internal/**


rate-limit:
  endpoints:
    - path: /api/contact
      max-requests: 3
      window-hours: 1
    - path: /api/currencies/convert
      max-requests: 8
      window-hours: 1
    - path: /api/pdf/reports/**
      max-requests: 14
      window-hours: 1
    - path: /api/email-change/request
      max-requests: 3
      window-hours: 1
    - path: /api/password-reset/request
      max-requests: 1
      window-hours: 1
    - path: /api/auth/register
      max-requests: 555  # 3
      window-hours: 1
    - path: /api/auth/login
      max-requests: 555 # 5
      window-hours: 1
    - path: /api/report-cache/refresh
      max-requests: 1
      window-minutes: 5
    - path: /api/revenue-history-cache/refresh
      max-requests: 1
      window-minutes: 5
    - path: /api/expense-history-cache/refresh
      max-requests: 1
      window-minutes: 5
    - path: /api/shared-accounts/report-cache/refresh
      max-requests: 1
      window-minutes: 5
    - path: /api/shared-account/users/send-invitation
      max-requests: 555 # 1
      window-hours: 1
    - path: /api/security-settings/additional-authorization/regenerate
      max-requests: 1
      window-hours: 24
    - path: /api/security-settings/additional-authorization/request-email-code
      max-requests: 66346 #3
      window-hours: 1
