server:
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: 1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - https://localhost:5173
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowed-headers:
                  - "*"
                allow-credentials: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          httpclient:
            ssl:
              use-insecure-trust-manager: true
          routes:
            - id: monolit
              uri: ${MONOLIT_URL}
              predicates:
                - Path=/**

logging:
  level:
    root: WARN
    com.finovara_backend.api_gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
