server:
  port: 8083
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: file:/app/localhost.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
    key-alias: 1

spring:
  application:
    name: finovara-report-service

core-backend:
  url: ${CORE_BACKEND_URL:https://finovara-app:8443}

expenses:
  highest:
    page-size: 5

revenues:
  highest:
    page-size: 5

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
