server:
  port: 8083
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: file:/app/localhost.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
    key-alias: 1

spring:
  application:
    name: finovara-report-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis
    redis:
      time-to-live: 180000  # 3 minutes
      cache-null-values: false
  kafka:
    bootstrap-servers: finovara-kafka:9092

finance-backend:
  url: ${FINANCE_BACKEND_URL:https://finovara-finance-app:8087}

expenses:
  highest:
    page-size: 5

revenues:
  highest:
    page-size: 5

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG

management:
  server:
    port: 9105
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: report-backend
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,500ms,1s,5s,10s
