spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finovara
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: finovaracenter@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
            trust: smtp.gmail.com
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
  upload:
    profile-images-directory: uploads/profile-images


mail:
  recipient:
    address: finovaracenter@gmail.com


user-activity:
  .login:
    page-size: 20
  .account-changes:
    page-size: 2