spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: finovara-security-monitoring-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:changelog/changelog.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: finovaracenter@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
            trust: smtp.gmail.com
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 8085
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: file:/app/localhost.p12
    key-store-type: PKCS12
    key-store-password: ${DEV_SSL_PASSWORD}
    key-alias: 1

auth-backend:
  url: ${AUTH_BACKEND_URL}

jwt:
  secret: ${JWT_KEY}

mail:
  recipient:
    address: ${MAIL_FROM_ADDRESS:finovaracenter@gmail.com}

email:
  secure-code:
    expires-at-minutes: 15

risk:
  transaction:
    expense-high-amount: 5000
    first-transaction-amount: 10000
    revenue-high-amount: 20000
    revenue-low-amount: 50
    piggy-bank-high-amount: 10000
    piggy-bank-diff-amount: 5000

    expense-high-points: 15
    expense-record-points: 20
    first-transaction-points: 25
    expense-category-points: 5
    revenue-high-points: 10
    revenue-low-points: 10
    piggy-bank-high-points: 15
    piggy-bank-diff-points: 10

  login:
    many-known-devices-threshold: 15
    impossible-travel-hours: 2

    unknown-device-points: 20
    unknown-location-points: 15
    impossible-travel-points: 40
    many-known-devices-points: 5
    partial-device-match-points: 15

  account-change:
    repeat-change-minutes: 15
    identity-change-minutes: 60
    new-account-days: 7
    new-account-change-count: 3

    repeat-change-points: 25
    identity-change-points: 35
    new-account-points: 30

  action:
    soft-challenge-points: 30
    authorization-points: 60
    full-verification-points: 85

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

management:
  server:
    port: 9106
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: security-monitoring-backend
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s