package com.finovara.securitymonitoring.riskengine.model;

public enum RiskRule {

    REPEAT_CHANGE,
    IDENTITY_REPAINT,
    NEW_ACCOUNT_MANY_CHANGES,

    UNKNOWN_DEVICE,
    UNKNOWN_LOCATION,
    IMPOSSIBLE_TRAVEL,
    MANY_KNOWN_DEVICES,
    PARTIAL_DEVICE_MATCH,

    EXPENSE_HIGH,
    EXPENSE_RECORD,
    FIRST_TRANSACTION_HIGH,
    EXPENSE_NEW_CATEGORY,
    REVENUE_HIGH,
    REVENUE_LOW,
    PIGGY_BANK_HIGH,
    PIGGY_BANK_DIFFERENT
}
