package com.finovara.activityservice.contracts.model.activity;

public enum PiggyBankActivityType {
    ADDED_PIGGY_BANK,
    DELETED_PIGGY_BANK,
    EDITED_PIGGY_BANK,
    AMOUNT_ADDED_TO_PIGGY_BANK_DIRECTLY,
    AMOUNT_ADDED_TO_PIGGY_BANK_BY_SETTING,
    AMOUNT_REMOVED_FROM_PIGGY_BANK,
    AMOUNT_REMOVED_FROM_PIGGY_BANK_BY_SETTING

}
