package com.finovara.contracts.model;

public enum NotificationType {
    LIMIT_EXCEEDED_WARNING,
    LIMIT_EXCEEDED,
    PIGGY_BANK_GOAL_APPROACHING,
    PIGGY_BANK_GOAL_REACHED,
    USER_ACCEPT_SHARED_ACCOUNT_INVITATION,
    USER_REJECT_SHARED_ACCOUNT_INVITATION,
    USER_SENT_SHARED_ACCOUNT_INVITATION,
    SHARED_ACCOUNT_INVITATION_EXPIRED,
    SHARED_ACCOUNT_DELETED,
    SHARED_ACCOUNT_LEFT,

    RECURRING_EXECUTION_SKIPPED
}
