spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://finovara-db:5432/finovara_db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:changelog/changelog.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: finovaracenter@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
            trust: smtp.gmail.com
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://localhost:8443/login/oauth2/code/google"
            scope:
              - openid
              - email
              - profile
server:
  port: 8443
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: 1

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
  upload:
    profile-images-directory: uploads/profile-images
    profile-images-default-directory: uploads/profile-images/default

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
mail:
  recipient:
    address: finovaracenter@gmail.com
  from:
    address: support@finovara.pl

nbp:
  api:
    url: https://api.nbp.pl/api
  properties:
    scale: 4

expenses:
  highest:
    page-size: 5


revenues:
  highest:
    page-size: 5



user-activity:
  login:
    page-size: 30
  account-changes:
    page-size: 30
  expense:
    page-size: 100
  revenue:
    page-size: 100
  limit:
    page-size: 100
  piggy-bank:
    page-size: 100
  settings:
    page-size: 100

notification-persistence:
  page-size: 5


scheduler:
  user-activity:
    login:
      archive-cron: "0 0 0 1 1/6 ?"
    account-changes:
      archive-cron: "0 0 0 1 1/6 ?"
    expense:
      delete-cron: "0 0 0 1 * ?"
    revenue:
      delete-cron: "0 0 0 1 * ?"
    limit:
      delete-cron: "0 0 0 1 * ?"
    piggy-bank:
      delete-cron: "0 0 0 1 * ?"
    settings:
      delete-cron: "0 0 0 1 * ?"
  recurring-settings:
    frequency: "0 0 0 * * ?"
  notification:
    delete-cron: "0 0 0 ? * 1"


verification-code-manager:
  code-expiration-minutes: 15
  attempts-expiration-minutes: 15
  max-attempts: 5


password-generator:
  length: 8


rate-limit:
  endpoints:
    - path: /api/contact
      max-requests: 3
      window-hours: 1
    - path: /api/currencies/convert
      max-requests: 8
      window-hours: 1
    - path: /api/pdf/reports/**
      max-requests: 14
      window-hours: 1


security:
  whitelist:
    - /api/auth/**
    - /api/profile-image/**
    - /profile-images/**
    - /api/password-reset/**
    - /api/contact
    - /oauth2/**
    - /login/oauth2/**
  cors:
    allowed-origins:
      - https://localhost:5173
