package com.finovara.contracts.model.activity;

public enum AccountChangesActivityType {
    PASSWORD_CHANGED,
    USERNAME_CHANGED,
    EMAIL_CHANGED,
    PROFILE_IMG_CHANGED,
    PROFILE_IMG_DELETED,
    ADDITIONAL_AUTHORIZATION_ENABLED,
    ADDITIONAL_AUTHORIZATION_DISABLED,
}