server:
  port: 8082
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: file:/app/localhost.p12
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
    key-alias: 1

spring:
  application:
    name: finovara-activity-service

  datasource:
    url: jdbc:postgresql://finovara-activity-db:5432/finovara_activity_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:changelog/changelog.xml
    enabled: true

  kafka:
    bootstrap-servers: finovara-kafka:9092

auth-backend:
  url: ${AUTH_BACKEND_URL}

scheduler:
  user-activity:
    login:
      archive-cron: "0 3 0 1 1/6 ?"
    account-changes:
      archive-cron: "0 5 0 1 1/6 ?"
    expense:
      delete-cron: "0 6 0 1 * ?"
    revenue:
      delete-cron: "0 10 0 1 * ?"
    limit:
      delete-cron: "0 15 0 1 * ?"
    piggy-bank:
      delete-cron: "0 20 0 1 * ?"
    settings:
      delete-cron: "0 25 0 1 * ?"
    shared-account:
      delete-cron: "0 30 0 1 * ?"

user-activity:
  login:
    page-size: 30
  account-changes:
    page-size: 30
  expense:
    page-size: 100
  revenue:
    page-size: 100
  limit:
    page-size: 100
  piggy-bank:
    page-size: 100
  settings:
    page-size: 100
  shared-account:
    page-size: 50


management:
  server:
    port: 9103
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics,scheduledtasks
  endpoint:
    health:
      show-details: always
    scheduledtasks:
      enabled: true
  metrics:
    tags:
      application: activity-log-backend
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s
